fieldLayouts:
  87357c29-754b-48e2-b4dc-7e10b6518822:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 80ceb32f-ea9f-4688-a3e5-fa50012f743a # First Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 04e6a877-0475-4f95-954a-9c6a13fdc551 # Last Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d82cd11f-ad62-447f-ab52-3db079bbaed3 # Favorite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5643e870-9641-4b8e-9468-77191f9ebfc0 # Season
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0a9728e5-9811-4ed3-b79f-95c47114b163 # Websites
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: chefs
hasTitleField: false
name: Chefs
section: dc40715c-5d22-433a-bd3b-23db348acf21 # Chefs
sortOrder: 1
titleFormat: '{{ firstName }} {{ lastName }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
