fieldLayouts:
  40fc10a9-5a85-4f6e-84d1-3a0410c7401b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 80ceb32f-ea9f-4688-a3e5-fa50012f743a # First Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 04e6a877-0475-4f95-954a-9c6a13fdc551 # Last Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0a9728e5-9811-4ed3-b79f-95c47114b163 # Websites
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: judges
hasTitleField: false
name: Judges
section: b033b0df-123d-4505-af9f-1db4f263fe16 # Judges
sortOrder: 1
titleFormat: '{{ firstName }} {{ lastName }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
