contentColumnType: string
fieldGroup: 4c8f489b-a3c0-464f-9c3b-0d1e2c672ed4 # Common
handle: city
instructions: ''
name: City
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:2ecd9912-b76c-4cee-bda0-eeba1e9de11c' # Cities
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
