contentColumnType: boolean
fieldGroup: 4c8f489b-a3c0-464f-9c3b-0d1e2c672ed4 # Common
handle: visited
instructions: ''
name: Visited
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
