enableVersioning: true
handle: restaurants
name: Restaurants
propagationMethod: all
siteSettings:
  82794e98-2fde-4a12-b668-d7f399670c48: # Top Chef Info
    enabledByDefault: true
    hasUrls: true
    template: restaurants/_entry
    uriFormat: 'restaurants/{slug}'
type: channel
